### PR TITLE
Implementing the Identity Server Auth Service for the rest of the project

### PR DESCRIPTION
**Pull request by ibnetahir1**
Created the Identity Server that talks to the rest of services in the application to provide authentication and authorization.

### CODE REVIEW

**Comment by escalonn** [comment]
merge the other PR to main and then merge down to here.
plus, set up for postgres instead of sql server, if that's what you're going to do

**Comment by escalonn** [comment]
add `sonar.exclusions=**/lib/**/*` to the sonar extra configs to ignore the bootstrap/jquery source code

**Comment by jpw547-zz** [comment]
To answer for how this code came to be: we pretty much just followed [this blog post](https://fullstackmark.com/post/21/user-authentication-and-identity-with-angular-aspnet-core-and-identityserver) and copied the [source code](https://github.com/mmacneil/AngularASPNETCoreOAuth/tree/master/src/AuthServer). We had already done some test implementations of IdentityServer on our own so by reading along with the blog we were able to keep up fairly well.

The only things that we changed/added to the code are:
- Added the following cookie policy to `Startup.cs`:
```app.UseCookiePolicy(new CookiePolicyOptions
            {
                HttpOnly = HttpOnlyPolicy.None,
                MinimumSameSitePolicy = SameSiteMode.Lax,
                Secure = CookieSecurePolicy.Always
            });
```

- We used the IS4 PersistentGrantDbContext instead of making our own

- Used Postgres instead of SqlServer like so in `Startup.cs`:
```
services.AddDbContext<AppIdentityDbContext>(options => options.UseNpgsql(Configuration.GetConnectionString("Default")));
...
services.AddIdentityServer()
                .AddDeveloperSigningCredential()
                // this adds the operational data from DB (codes, tokens, consents)
                .AddOperationalStore<PersistedGrantDbContext>(options =>
                {
                    options.ConfigureDbContext = builder => builder.UseNpgsql(Configuration.GetConnectionString("Default"), sql => sql.MigrationsAssembly("AuthServer.Infrastructure"));
                    // this enable automatic token cleanup. this is optional
                    options.EnableTokenCleanup = true;
                    options.TokenCleanupInterval = 30; // interval in seconds
                })
                ...
```

- We also had to add a `Redirect.cshtml` view in the `AuthServer/Views/Account` folder to avoid an error that occurred.

**Comment by jpw547-zz** [comment]
If you're fine with it as well I'll make a new branch tomorrow to start fixing code smells and other issues reported by SonarCloud.

**Review by escalonn — APPROVED** [review]
- address my previous comment in the next PR then
- the TokenCleanupInterval value is reasonable? it's 2 orders of magnitude shorter than the default value, but if you think it's fine then ok

**Pull request merged**
